In [2]:
import pandas as pd
import numpy as np
import openpyxl
import xlrd

In [6]:
data = pd.read_csv('./data/goms_feature_prep_com.csv', header=1) # 각자 경로로 바꾸기
data

,jobseekAftGradu,jobseekAftGradu_str,workWithin1yr,workWithin1yr_str,wishWorkHr,wishSalary,JobYNaftGradu,JobYNaftGradu_str,wayTolivexpense,wayTolivexpense_str,...,jobseekYN,certNum,mainJobCate,mainJobCate_str,midJobCate,midJobCate_str,subJobCate,subJobCate_str,jobYN_str,jobYN
0,2,아니오,2,아니오,0,0,2,아니오,1,일자리에서의 근로 소득,...,1,0,6,미용·여행·숙박·음식·경비·청소직,20,경호·경비직,541,경호·보안종사자,근로자,1
1,1,예,2,아니오,3,2400,2,아니오,-1,모름/무응답,...,1,0,0,무직,0,무직,0,무직,무직자,0
2,2,아니오,2,아니오,0,0,2,아니오,3,가족 친지로부터의 지원,...,0,1,3,교육·법률·사회복지·경찰·소방직및군인,9,교육직,214,문리·기술·예능강사,근로자,1
3,2,아니오,2,아니오,0,0,2,아니오,1,일자리에서의 근로 소득,...,0,0,6,미용·여행·숙박·음식·경비·청소직,18,여행·숙박·오락 서비스직,522,항공기·선박·열차객실승무원,근로자,1
4,2,아니오,2,아니오,0,0,2,아니오,1,일자리에서의 근로 소득,...,1,1,7,영업·판매·운전·운송직,23,영업·판매직,615,판매종사자,근로자,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18158,2,아니오,2,아니오,0,0,1,예,-1,모름/무응답,...,1,0,0,무직,0,무직,0,무직,무직자,0
18159,2,아니오,2,아니오,0,0,2,아니오,1,일자리에서의 근로 소득,...,0,0,3,교육·법률·사회복지·경찰·소방직및군인,9,교육직,214,문리·기술·예능강사,근로자,1
18160,2,아니오,2,아니오,0,0,1,예,1,일자리에서의 근로 소득,...,0,0,7,영업·판매·운전·운송직,23,영업·판매직,612,영업원및상품중개인,근로자,1
18161,2,아니오,2,아니오,2,3000,2,아니오,-1,모름/무응답,...,0,0,0,무직,0,무직,0,무직,무직자,0
18162,2,아니오,2,아니오,0,0,2,아니오,2,"금융, 부동산 등의 본인 재산",...,0,1,3,교육·법률·사회복지·경찰·소방직및군인,9,교육직,213,유치원교사,근로자,1

In [18]:

data_main = data[['jobseekAftGradu', 'workWithin1yr', 'wishWorkHr', 'wishSalary',
       'JobYNaftGradu', 'wayTolivexpense', 'schoolType', 'majorCate', 'age',
       'internExp', 'toeicScore', 'tospGrade', 'trainingHr', 'jobseekYN',
       'certNum', 'midJobCate']]
data_main

,jobseekAftGradu,workWithin1yr,wishWorkHr,wishSalary,JobYNaftGradu,wayTolivexpense,schoolType,majorCate,age,internExp,toeicScore,tospGrade,trainingHr,jobseekYN,certNum,midJobCate
0,2,2,0,0,2,1,1,1,23,0,0,0,0,1,0,20
1,1,2,3,2400,2,-1,1,1,21,0,0,0,240,1,0,0
2,2,2,0,0,2,3,1,1,21,0,800,0,0,0,1,9
3,2,2,0,0,2,1,1,1,25,0,0,0,0,0,0,18
4,2,2,0,0,2,1,1,1,21,0,0,0,0,1,1,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18158,2,2,0,0,1,-1,2,181,27,0,0,0,0,1,0,0
18159,2,2,0,0,2,1,2,181,25,0,0,0,0,0,0,9
18160,2,2,0,0,1,1,2,181,26,0,0,0,0,0,0,23
18161,2,2,2,3000,2,-1,1,20,28,0,0,0,0,0,0,0
18162,2,2,0,0,2,2,1,20,27,0,0,0,0,0,1,9

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier


from sklearn.ensemble import RandomForestClassifier # 분류는 사용 필요 x
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score

from xgboost import XGBRegressor
from xgboost import XGBClassifier
from xgboost import plot_importance

In [19]:
y_main = data_main['midJobCate']
x_main = data_main.drop(['midJobCate'],axis=1)

X_train, X_test, y_train, y_test = train_test_split(x_main, y_main, test_size=0.3, random_state=0)
dtr = DecisionTreeRegressor(max_depth=3, random_state=12)
dtr.fit(X_train, y_train)

rfr = RandomForestRegressor(max_depth = 3,random_state=12)
rfr.fit(X_train, y_train)

xgbr = XGBRegressor(objective='reg:squarederror', max_depth=3, random_state=12)
xgbr.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=32, num_parallel_tree=1, random_state=12,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [20]:
x_main

,jobseekAftGradu,workWithin1yr,wishWorkHr,wishSalary,JobYNaftGradu,wayTolivexpense,schoolType,majorCate,age,internExp,toeicScore,tospGrade,trainingHr,jobseekYN,certNum
0,2,2,0,0,2,1,1,1,23,0,0,0,0,1,0
1,1,2,3,2400,2,-1,1,1,21,0,0,0,240,1,0
2,2,2,0,0,2,3,1,1,21,0,800,0,0,0,1
3,2,2,0,0,2,1,1,1,25,0,0,0,0,0,0
4,2,2,0,0,2,1,1,1,21,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18158,2,2,0,0,1,-1,2,181,27,0,0,0,0,1,0
18159,2,2,0,0,2,1,2,181,25,0,0,0,0,0,0
18160,2,2,0,0,1,1,2,181,26,0,0,0,0,0,0
18161,2,2,2,3000,2,-1,1,20,28,0,0,0,0,0,0
18162,2,2,0,0,2,2,1,20,27,0,0,0,0,0,1

In [21]:

y_train_pred = dtr.predict(X_train)
train_mse = mean_squared_error(y_train, y_train_pred)
print("Train MSE: %.4f" % train_mse)

y_test_pred = dtr.predict(X_test)
test_mse = mean_squared_error(y_test, y_test_pred)
print("Test MSE: %.4f" % test_mse)

Train MSE: 45.6006
Test MSE: 46.5201

In [22]:
dt=DecisionTreeClassifier(random_state=0)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [23]:

y_train_pred = rfr.predict(X_train)
train_mse = mean_squared_error(y_train, y_train_pred)
print("Train MSE: %.4f" % train_mse)

y_test_pred = rfr.predict(X_test)
test_mse = mean_squared_error(y_test, y_test_pred)
print("Test MSE: %.4f" % test_mse)

y_train_pred = rfr.predict(X_train)

Train MSE: 45.1510
Test MSE: 46.0387

In [24]:

rf=RandomForestClassifier(random_state=0, max_depth=4)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=4, random_state=0)

In [25]:
pred=rf.predict(X_test)
print("정확도:{0:.3f}".format(accuracy_score(y_test,pred)))

정확도:0.483

In [26]:
y_train_pred = xgbr.predict(X_train)
train_mse = mean_squared_error(y_train, y_train_pred)
print("Train MSE: %.4f" % train_mse)

y_test_pred = xgbr.predict(X_test)
test_mse = mean_squared_error(y_test, y_test_pred)
print("Test MSE: %.4f" % test_mse)

Train MSE: 39.6405
Test MSE: 43.3489

In [27]:
xgb=XGBClassifier(n_estimators=100,learning_rate=0.1,max_depth=4)
xgb.fit(X_train,y_train)
xgb_pred=xgb.predict(X_test)

C:\Python\Python36\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[11:01:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [28]:
accuracy_score(y_test,xgb_pred)
print("정확도:{0:.3f}".format(accuracy_score(y_test,xgb_pred)))

정확도:0.616